# Travis-CI file for Espruino

language: c

# Maybe someday when travis-ci authorizes the ppa:
# https://github.com/travis-ci/apt-source-whitelist/issues/132
#sudo: false
#addon:
#  apt:
#    sources:
#      - ppa:team-gcc-arm-embedded/ppa
#    packages:
#      - libsdl1.2-dev gcc-arm-embedded

before_install:
 - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
 - sudo apt-get update
 - sudo apt-get install libsdl1.2-dev gcc-arm-embedded
 - curl -Ls http://s3.voneicken.com/xtensa-lx106-elf-20160330.tgx | tar Jxf -
 - curl -Ls http://s3.voneicken.com/esp_iot_sdk_v2.0.0.p1.tgx | tar Jxf -
 - curl -Ls https://github.com/espruino/EspruinoBuildTools/raw/master/esp32/deploy/app.tgz | tar xfz -
 - curl -Ls https://github.com/espruino/EspruinoBuildTools/raw/master/esp32/deploy/esp-idf.tgz | tar xfz -
 - curl -Ls https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-61-gab8375a-5.2.0.tar.gz | tar xfz -
before_script:
 - arm-none-eabi-gcc --version
 - xtensa-esp32-elf-gcc --version

after_script:
  - ls *.bin *.hex *.tgz | xargs -I {} curl -v -F "binary=@{}" "http://www.espruino.com/travis_upload.php?commit=$TRAVIS_COMMIT"
  # upload to an S3 bucket, requires S3_BUCKET, AWS_ACCESS_KEY_ID and AWS_SECRET_KEY to be set
  # in environment using travis' repository settings
  - "if [[ -n \"$S3_BUCKET\" && -n \"$AWS_ACCESS_KEY_ID\" ]]; then
      echo Uploading *.tgz to $S3_BUCKET;
      curl -Ls https://github.com/rlmcpherson/s3gof3r/releases/download/v0.5.0/gof3r_0.5.0_linux_amd64.tar.gz | tar zxf - gof3r_0.5.0_linux_amd64/gof3r;
      mv gof3r*/gof3r .;
      ls *.tgz | xargs -I {} ./gof3r put -b $S3_BUCKET -k espruino/{} --acl public-read -p {};
      ls *.tgz | xargs -I {} echo \"URL: http://$S3_BUCKET/espruino/{}\";
      fi"

compiler:
  - gcc

env:
  global:
    - RELEASE=1
    - TRAVIS=1
    - V=0
    - ESP8266_SDK_ROOT=$TRAVIS_BUILD_DIR/esp_iot_sdk_v2.0.0.p1
    - PATH=$PATH:$TRAVIS_BUILD_DIR/xtensa-lx106-elf/bin/
    -  ESP_IDF_PATH=$TRAVIS_BUILD_DIR/esp-idf
    -  ESP_APP_TEMPLATE_PATH=$TRAVIS_BUILD_DIR/app
    -  RELEASE=1
    -  PATH=$PATH:$TRAVIS_BUILD_DIR/xtensa-esp32-elf/bin/
  matrix:
    - ESP32=1
    - ESP8266_BOARD=1
#    - ESPRUINO_1V3=1
    - PICO_1V3=1
#    - MICROBIT=1
#    - NRF52832DK=1
#    - OLIMEXINO_STM32=1
#    - MAPLERET6_STM32=1
#    - HYSTM32_24=1
#    - HYSTM32_28=1
#    - HYSTM32_32=1
#    - STM32VLDISCOVERY=1
#    - STM32F3DISCOVERY=1
#    - STM32F4DISCOVERY=1
#    - NUCLEOF401RE=1
#    - NUCLEOF411RE=1
#    - LCTECH_STM32F103RBT6=1
    - LINUX_BUILD=1
#    - EFM32GGSTK=1
#    - NUCLEOL476RG=1
script: make -j 4

notifications:
  email: false
  
